coverage:
  status:
    project: off
    patch: off

comment:
  layout: "condensed_header, diff, flags, components"

component_management:
  individual_components:
    - component_id: api-calculator  # this is an identifier that should not be changed
      name: calculator  # this is a display name, and can be changed freely
      paths:
        - api/calculator/
    - component_id: api-smiles  # this is an identifier that should not be changed
      name: smiles  # this is a display name, and can be changed freely
      paths:
        - api/smiles/

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: backend
      paths:
        - api/
      statuses:
        - type: project
          target: 80%
          threshold: 1%
    - name: frontend
      paths:
        - web/
      statuses:
        - type: project
          target: auto
          threshold: 1%
